services:
  web:
    build: .
    ports:
      - "5000:5000"  # expose your Flask app on port 5000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: githubdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kalekye1222
    ports:
      - "5433:5432"  # HOST:CONTAINER — expose PostgreSQL on localhost:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
